version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always

    env_file:
      - .env.prod

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - ${DATABASE_PORT}:5432
    
    networks:
      - gateway

    volumes:
      - ./db:/var/lib/postgresql/data

  gateway:
    build:
      context: ./
      dockerfile: Dockerfile

    links:
      - "db:database"

    env_file:
      - .env.prod

    restart: always
    depends_on:
      - db
    
    networks:
      - gateway

networks:
  gateway:
    name: gateway