version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always

    env_file:
      - ./.env.prod

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./db:/data/db
    networks:
      - gateway

  discord-bot:
    container_name: discord-bot
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - mongodb
    
    env_file:
      - ./.env.prod

    networks:
      - gateway

networks:
  gateway:
    external: true